//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNSWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl welcomePageDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl aboutPageDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl hoursPageDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl menuPageDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl estimatesDiv;
		
		protected System.Web.UI.WebControls.Table estimatesTable;
		
		protected System.Web.UI.WebControls.Label desertTypeLbl;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl cakeForm2Div;
		
		protected System.Web.UI.WebControls.DropDownList desertTypeDdl;
		
		protected System.Web.UI.WebControls.TextBox servingsTBox;
		
		protected System.Web.UI.WebControls.DropDownList cakeFlavorDdl;
		
		protected System.Web.UI.WebControls.DropDownList frostingFlavorDdl;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl galleryDiv;
		
		protected System.Web.UI.WebControls.Table galleryTable;
		
		protected System.Web.UI.WebControls.TableRow galleryTableRow;
		
		protected System.Web.UI.WebControls.TableCell slideShowCell;
	}
}
